apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  bootstrap: true
  repo: https://helm.cilium.io/
  chart: cilium
  version: 1.19.1
  targetNamespace: kube-system
  valuesContent: |-
    MTU: 1350
    devices: "wireguard"
    operator:
      replicas: 1
    kubeProxyReplacement: true
    k8sServiceHost: "kamrui-p1.wireguard"
    k8sServicePort: "6443"
    ipv4:
      enabled: true
    ipv6:
      enabled: true