apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netmaker
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netmaker
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true  
  source:
    chart: netmaker
    repoURL: https://gravitl.github.io/netmaker-helm/
    targetRevision: 1.4.0
    helm:
      releaseName: netmaker
      values: |
        baseDomain: "andrewlee.cloud"

        ui:
          replicas: 1

        server:
          RWX:
            storageClassName: "longhorn"
          storageSize: 4Gi

        dns:
          enabled: false

        ingress:
          enabled: false

        postgresql-ha:
          enabled: true
          persistence:
            size: 4Gi
       
