{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.clan-net.services.headscale;
in {
  # Define a new option for the admin user
  options.clan-net.services.headscale = {
    enable = lib.mkEnableOption "headscale";
    base_domain = lib.mkOption {
      type = lib.types.str;
      default = "example.com";
      description = "Domain for the headscale server";
    };
    adminUser = lib.mkOption {
      type = lib.types.str;
      default = "admin@example.com";
      description = "headscale admin user";
    };
    client_id = lib.mkOption {
      type = lib.types.str;
      default = "12345.apps.googleusercontent.com";
      description = "Client ID for OIDC (default Google)";
    };
    issuer = lib.mkOption {
      type = lib.types.str;
      default = "https://accounts.google.com";
      description = "OIDC issuer (default Google)";
    };
    allowed_domains = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Allowed domains for OIDC";
    };
    allowed_users = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Allowed domains for OIDC";
    };
    aclConfig = lib.mkOption {
      type = lib.types.attrs;
      default = {
        # Groups definition
        groups = {
          "group:admins" = ["${cfg.adminUser}"];
        };

        acls = [
          # Allow all connections within the tailnet
          {
            action = "accept";
            src = ["*"];
            dst = ["*:*"];
          }
          # Allow admin to connect to their own services
          {
            action = "accept";
            src = ["${cfg.adminUser}"];
            dst = ["${cfg.adminUser}:*"];
          }
        ];

        # Auto-approvers section for routes
        autoApprovers = {
          routes = {
            "0.0.0.0/0" = [cfg.adminUser];
            "10.0.0.0/8" = [cfg.adminUser];
            "192.168.0.0/16" = [cfg.adminUser];
          };

          exitNode = [cfg.adminUser];
        };
      };
      description = "Headscale ACL configuration";
    };
  };

  config = let
    inherit (cfg) adminUser base_domain aclConfig;
    # Convert to HuJSON format with comments
    aclHuJson = ''
      // Headscale ACL Policy - Generated by NixOS
      // Admin user: ${adminUser}

      ${builtins.toJSON aclConfig}
    '';
    aclFile = pkgs.writeText "acl-policy.hujson" aclHuJson;
  in
    lib.mkIf cfg.enable {
      clan.core.vars.generators."vpn.${base_domain}" = {
        share = true;
        prompts = {
          client_secret = {
            persist = true;
            description = "Client secret for OIDC";
            display.group = "vpn.${base_domain}";
          };
          client_id = {
            description = "Client ID for OIDC";
            display.group = "vpn.${base_domain}";
          };
        };
        files = {
          client_secret = {};
          client_id.secret = false;
        };
      };

      services.headscale = {
        enable = true;
        port = 9999;
        address = "0.0.0.0";
        settings = {
          policy.path = aclFile;
          log.format = "json";
          server_url = "https://vpn.${base_domain}:443";
          dns = {
            inherit (cfg) base_domain;
            nameservers.global = ["8.8.8.8"];
            search_domains = ["${base_domain}.internal"];
          };
          oidc = {
            inherit (cfg) issuer allowed_domains allowed_users;
            client_secret_path = config.clan.core.vars.generators."vpn.${base_domain}".files.client_secret.path;
            client_id = config.clan.core.vars.generators."vpn.${base_domain}".files.client_id.value;
          };
        };
      };

      # Create a systemd service to ensure the admin user exists
      systemd.services.headscale-ensure-admin = {
        description = "Ensure Headscale admin user exists";
        after = ["headscale.service"];
        requires = ["headscale.service"];
        wantedBy = ["multi-user.target"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          User = "headscale";
          Group = "headscale";
        };

        script = ''
          # Check if user exists and create if needed
          if ! ${pkgs.headscale}/bin/headscale users list | grep -q "${adminUser}"; then
            echo "Creating headscale admin user: ${adminUser}"
            ${pkgs.headscale}/bin/headscale users create "${adminUser}"
          else
            echo "Headscale admin user ${adminUser} already exists"
          fi
        '';
      };

      # nginx reverse proxy for headscale
      services.nginx.virtualHosts."vpn.${base_domain}" = {
        forceSSL = true;
        useACMEHost = base_domain;
        locations."/" = {
          proxyPass = "http://localhost:${toString config.services.headscale.port}";
          proxyWebsockets = true;
        };
      };
    };
}
