{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.clan-net.services.headscale;
in {
  # Define a new option for the admin user
  options.clan-net.services.headscale = {
    enable = lib.mkEnableOption "headscale";
    base_domain = lib.mkOption {
      type = lib.types.str;
      default = "vpn.${config.clan.core.settings.domain}";
      description = "Domain for the headscale server";
      example = "headscale.example.com";
    };
    adminUser = lib.mkOption {
      type = lib.types.str;
      default = "super-admin";
      description = "headscale admin user";
      example = "my-user";
    };
    adminEmail = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.adminUser}@gmail.com";
      description = "headscale admin email";
      example = "admin@example.com";
    };
    issuer = lib.mkOption {
      type = lib.types.str;
      default = "https://accounts.google.com";
      description = "OIDC issuer (default Google)";
    };
    allowed_domains = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Allowed domains for OIDC";
    };
    allowed_users = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Allowed users for OIDC";
    };
    aclConfig = lib.mkOption {
      type = lib.types.attrs;
      default = {
        # Groups definition
        groups = {
          "group:admins" = ["${cfg.adminUser}"];
        };

        acls = [
          # Allow all connections within the tailnet
          {
            action = "accept";
            src = ["*"];
            dst = ["*:*"];
          }
          # Allow admin to connect to their own services
          {
            action = "accept";
            src = ["${cfg.adminUser}"];
            dst = ["${cfg.adminUser}:*"];
          }
        ];

        # Auto-approvers section for routes
        autoApprovers = {
          routes = {
            "10.0.0.0/8" = [cfg.adminUser];
          };

          exitNode = [cfg.adminUser];
        };
      };
      description = "Headscale ACL configuration";
    };
    derp.enabled = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable DERP (WireGuard) support";
      example = true;
    };
    derp.ipv4 = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "DERP IPv4 address";
      example = "198.51.100.1";
    };
    derp.ipv6 = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "DERP IPv6 address";
      example = "2001:db8::1";
    };
  };

  config = let
    inherit (cfg) adminUser adminEmail base_domain aclConfig;
    # Convert to HuJSON format with comments
    aclHuJson = ''
      // Headscale ACL Policy - Generated by NixOS
      // Admin user: ${adminUser}

      ${builtins.toJSON aclConfig}
    '';
    aclFile = pkgs.writeText "acl-policy.hujson" aclHuJson;
  in
    lib.mkIf cfg.enable {
      clan.core.vars.generators."headscale.${base_domain}" = {
        share = true;
        prompts = {
          client_secret = {
            persist = true;
            description = "Client secret for OIDC";
            display.group = base_domain;
          };
          client_id = {
            description = "Client ID for OIDC";
            display.group = base_domain;
          };
        };
        files = {
          client_secret = {
            owner = config.services.headscale.user;
            group = config.services.headscale.group;
          };
          client_id.secret = false;
        };
        runtimeInputs = [pkgs.coreutils];
        script = ''
          mkdir -p $out
          cp $prompts/* $out/
        '';
      };

      services.headscale = {
        enable = true;
        port = 9999;
        address = "0.0.0.0";
        settings = {
          policy.path = aclFile;
          log.format = "json";
          server_url = "https://headscale.${base_domain}:443";
          dns = {
            base_domain = "ts.${base_domain}";
            nameservers.global = ["8.8.8.8"];
          };
          oidc = {
            inherit (cfg) issuer allowed_domains allowed_users;
            client_secret_path = config.clan.core.vars.generators."headscale.${base_domain}".files.client_secret.path;
            client_id = config.clan.core.vars.generators."headscale.${base_domain}".files.client_id.value;
          };
          derp.server = {
            inherit (cfg.derp) enabled ipv4 ipv6;
            stun_listen_addr = "0.0.0.0:3478";
            automatically_add_embedded_derp_region = true;
          };
        };
      };

      # Allow headscale to bind to UDP ports 41641 and 3478 for WireGuard
      networking.firewall.allowedUDPPorts = [41641 3478];

      # Create a systemd service to ensure the admin user exists
      systemd.services.headscale-ensure-admin = {
        description = "Ensure Headscale admin user exists";
        after = ["headscale.service"];
        requires = ["headscale.service"];
        wantedBy = ["multi-user.target"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          User = "headscale";
          Group = "headscale";
        };

        script = ''
          # Check if user exists and create if needed
          if ! ${pkgs.headscale}/bin/headscale users list | grep -q "${adminUser}"; then
            echo "Creating headscale admin user: ${adminUser}"
            ${pkgs.headscale}/bin/headscale users create "${adminUser}" --email "${adminEmail}"
          else
            echo "Headscale admin user ${adminUser} already exists"
          fi
        '';
      };

      # nginx reverse proxy for headscale
      services.nginx.virtualHosts."headscale.${base_domain}" = {
        forceSSL = true;
        enableACME = true;
        locations."/" = {
          proxyPass = "http://localhost:${toString config.services.headscale.port}";
          proxyWebsockets = true;
        };
      };
    };
}
